INSERT INTO INSURANCE_AGENTS (AGENT_ID, AGENT_FIRST_NAME, AGENT_LAST_NAME, AGENT_MIDDLE_INITIAL, AGENT_ADDRESS_LINE1, AGENT_ADDRESS_LINE2, AGENT_CITY, AGENT_STATE_ID, AGENT_POSTALCODE, AGENT_EMAIL, AGENT_PASSWORD, AGENT_ACTIVE_YESNO, AGENT_EXPENSE_ENABLED_YESNO, COMPANY) 
VALUES (1,"MURRAY","SIMPSON","G", "201 Wicksteed Avenue", "ZOO PARK", "ATLANTA", "2", "30068",  "MURRAY.SIMPSON@NICORDESIGNS.TECH", "secret", "Y", "Y", "BIGLEY");

INSERT INTO INSURANCE_AGENTS (AGENT_ID, AGENT_FIRST_NAME, AGENT_LAST_NAME, AGENT_MIDDLE_INITIAL, AGENT_ADDRESS_LINE1, AGENT_ADDRESS_LINE2, AGENT_CITY, AGENT_STATE_ID, AGENT_POSTALCODE, AGENT_EMAIL, AGENT_PASSWORD, AGENT_ACTIVE_YESNO, AGENT_EXPENSE_ENABLED_YESNO, COMPANY) 
VALUES (2,"CARLA","MENDES", "L", "45575 Keith Wilson Rd", "L5P", "ATLANTA", "2", "30338",  "CARLA.MENDES@NICORDESIGNS.TECH", "secret", "Y", "Y", "A1");

INSERT INTO INSURANCE_AGENTS (AGENT_ID, AGENT_FIRST_NAME, AGENT_LAST_NAME, AGENT_MIDDLE_INITIAL, AGENT_ADDRESS_LINE1, AGENT_ADDRESS_LINE2, AGENT_CITY, AGENT_STATE_ID, AGENT_POSTALCODE, AGENT_EMAIL, AGENT_PASSWORD, AGENT_ACTIVE_YESNO, AGENT_EXPENSE_ENABLED_YESNO, COMPANY) 
VALUES (3,"DERRICK","CAMPOS", "A", "2572 Johnson RD", "BUCKHEAD", "ATLANTA", "2", "30101",  "DERRICK.CAMPOS@NICORDESIGNS.TECH", "secret", "Y", "Y", "A1");

INSERT INTO INSURANCE_AGENTS (AGENT_ID, AGENT_FIRST_NAME, AGENT_LAST_NAME, AGENT_MIDDLE_INITIAL, AGENT_ADDRESS_LINE1, AGENT_ADDRESS_LINE2, AGENT_CITY, AGENT_STATE_ID, AGENT_POSTALCODE, AGENT_EMAIL, AGENT_PASSWORD, AGENT_ACTIVE_YESNO, AGENT_EXPENSE_ENABLED_YESNO, COMPANY) 
VALUES (4,"DORIS","HUMAN", "B", "12 LOOP STR", "BUCKHEAD", "ATLANTA", "2", "30901",  "DORIS.HUMAN@NICORDESIGNS.TECH", "secret", "Y", "Y", "A1");

