INSERT INTO ADMIN_USER (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD) VALUES (1,"PETER","PARKER","pete.parker@insuranceco.com", "secret");
INSERT INTO ADMIN_USER (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD) VALUES (2,"BABY","SHARK","baby@sharkmail.com", "secret");
INSERT INTO ADMIN_USER (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD) VALUES (3,"HOMER","SIMPSON","doh@nukemail.com", "secret");
