--  ALTER TABLE `PROVINCES` DROP CONSTRAINT `PK_PROVINCE`;

--  DROP INDEX `PK_PROVINCE`;

--  DROP TABLE `PROVINCES`;

CREATE TABLE `PROVINCES` (
		`PROVINCEID` DECIMAL(22 , 0) NOT NULL,
		`PROVINCENAME` VARCHAR(50),
		`PROVINCE_TAXRATE` VARCHAR(10),
		`PROVINCECODE` VARCHAR(2),
		`PROVINCENAME_FR` VARCHAR(50),
		`ALIS_PROVINCE_CODE` DECIMAL(22 , 0)
	);

CREATE UNIQUE INDEX `PK_PROVINCE` ON `PROVINCES` (`PROVINCEID` ASC);

ALTER TABLE `PROVINCES` ADD CONSTRAINT `PK_PROVINCE` PRIMARY KEY (`PROVINCEID`);
