ALTER TABLE `STATES` DROP INDEX `PK_STATE`;

DROP TABLE `STATES`;

CREATE TABLE `STATES` (
		`STATE_ID` DECIMAL(22 , 0) NOT NULL,
		`STATE_NAME` VARCHAR(50),
		`STATE_TAXRATE` VARCHAR(10),
		`STATE_CODE` VARCHAR(2)
	);

CREATE UNIQUE INDEX `PK_STATE` ON `STATES` (`STATE_ID` ASC);

ALTER TABLE `STATES` ADD CONSTRAINT `PK_STATE` PRIMARY KEY (`STATE_ID`);
